### ISSUE TITLE
Embedded 'common::sense' clone hides the original

### ISSUE THREAD

**Issue by gsimon75** [logie17/Dancer-Plugin-Swig#3]
When some automated mechanism (Alpine's `apkbuild-cpan` in my case) tries to obtain the prerequisites for `common::sense`, the link http://search.cpan.org/api/module/common::sense finds your module instead, and then the recursive crawler starts pullin in the whole Dancer ecosystem with all its cumulative prerequisites.

For manual installation it's not a big deal to choose the appropriate `common::sense`, but for automated crawlers it's a disaster.

If you decided to clone/fork that other module instead of just depending on it, could you please rename it to avoid confusions?

**Comment by logie17** [comment]
This was a mistake I did a few years ago out of ignorance and I did attempt to fix it in the most recent version of this module, however, I have been told I need to remove the bad version from PAUSE. This is what I have done, and I hope it fixes your automated crawler:

![screen shot 2018-05-29 at 2 23 25 pm](https://user-images.githubusercontent.com/169981/40686406-11dd2b4c-634c-11e8-99e2-8344c2203f68.png)

Thanks for letting me know about this issue, and hopefully it should resolve itself soon!

Cheers!
Logan

**Comment by logie17** [comment]
I fixed my end of things: GET http://search.cpan.org/api/module/common::sense ```
{
   "version" : "3.74",
   "abstract" : "save a tree AND a kitten, use common::sense! ",
   "module" : "common::sense",
   "archive" : "Types-Bool-2.98001-TRIAL.tar.gz",
   "distvname" : "Types-Bool-2.98001-TRIAL",
   "status" : "testing",
   "authorized" : false,
   "cpanid" : "FERREIRA"
}
```
